export const FORM_TOOLTIPS = {
    companyName: "Enter the company's registered legal name as it appears on official documents.",
    companyWebsite: "The company's official website URL. This helps verify the business presence.",
    businessType: "Select the category that best describes the company's primary business operations.",
    companySize: "Approximate number of full-time employees in the organization.",
    yearEstablished: "Enter the year your company was officially established.",
    addressLine1: "Provide the primary business address.",
    addressLine2: "Optional: Additional address details like suite number, floor, or landmark.",
    city: "Enter the city where your company is located.",
    state: "Enter the state or region of your business address.",
    postalCode: "Enter the postal or ZIP code for your business location.",
    country: "Select the country where your business operates.",
    primaryContactName: "Full name of the primary contact person for all supplier communication.",
    primaryContactRole: "Job title or role of the primary contact person in the organization.",
    primaryContactEmail: "Official email address for communication.",
    primaryContactNumber: "Main phone number for urgent communications. Include country code if applicable (e.g., +91).",
    secondaryContactName: "Full name of the secondary contact person for all supplier communication.",
    secondaryContactRole: "Job title or role of the secondary contact person in the organization.",
    secondaryContactEmail: "Secondary email address for communication.",
    secondaryContactPhone: "Secondary phone number for urgent communications. Include country code if applicable (e.g., +91).",
    companyOverview: "Brief description of your company, services, and expertise.",
    certifications: "Industry certifications the company holds (e.g., ISO 9001, CMMI Level 3). Add multiple by typing and clicking 'Add'.",

    employeeId: "Your company’s internal employee ID for this person.",
    workingSince: "The date the individual started working with your organisation.",
    ctc: "Annual CTC used only for benchmarking and planning.",
    jobTitle: "Current internal job title/designation.",
    role: "Primary capacity role/category (e.g., Full Stack Developer).",
    gender: "Used only for high-level reporting; no personal contact data is collected.",
    location: "Work location band/city for readiness planning.",
    experience: "Total years of professional experience.",
    skills: "Core technical skills (comma-separated).",
    tools: "Tools/platforms used (e.g., Git, Docker, Jira).",
    projects: "Number of projects completed/handled (approximate).",
  };